name: household_ai_engineer
description: "Flutter dashboard for the Household Software Engineer system - a native macOS application for creating and managing custom household applications."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Used to define localizable strings
  flutter_localizations:
    sdk: flutter
  # Used to send REST API commands
  http: ^1.5.0
  # Path utilities
  path: ^1.9.0
  # Local storage and preferences
  shared_preferences: ^2.2.2
  # StreamChannel wrappers for WebSockets.
  web_socket_channel: ^3.0.3
  # Window management for macOS
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lint rules for Dart and Flutter used internally at Very Good Ventures
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
